name: latihan_moor_db
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  moor_flutter: 4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: 2.1.8
  moor_generator: 4.6.0+1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

